In [1]:
import numpy as np
import pandas as pd

In [2]:
# Make sure we use the correct venv

import sys
print(sys.prefix)

C:\Users\molok\AppData\Local\pypoetry\Cache\virtualenvs\lpp-6NAJWl0s-py3.10


In [3]:
dd_df = pd.read_excel('../datasets/demo.xlsx')

In [4]:
dd_df.head(10)

SubjectID  Age  Sex(0-f,1-m)  IQ  L1_lexical_skill  L1_spelling_skill  \
0     rum_1   30           0.0   7                79                 57   
1     rum_2   20           0.0  10                74                 44   
2     rum_3   20           0.0   7                83                 58   
3     rum_4   20           0.0   5                78                 43   
4     rum_5   29           0.0   8                87                 59   
5     rum_6   17           0.0   9                78                 45   
6     rum_7   19           0.0   8                85                 55   
7     rum_8   21           0.0   6                80                 45   
8     rum_9   21           0.0   7                74                 47   
9    rum_10   21           0.0  10                82                 60   

  English_Level  L2_spelling_skill  L2_vocabulary_size  L2_lexical_skill  
0            C2               39.0                71.0             81.25  
1            C1               35.0                85.0             90.00  
2            C2               39.0                85.0             96.25  
3            C2               38.0                72.0             90.00  
4            C2               44.0                76.0             86.25  
5            C1               35.0                83.0             65.00  
6            C2               40.0                66.0             83.75  
7            C2               38.0                43.0             81.25  
8            C1               40.0                 6.0             72.50  
9            C1               39.0                 NaN             75.00

In [25]:
arr = np.repeat(np.arange(12).reshape(1,-1), 3, axis=0)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [29]:
np.asarray(arr > 5)

array([[False, False, False, False, False, False,  True,  True,  True,
         True,  True,  True],
       [False, False, False, False, False, False,  True,  True,  True,
         True,  True,  True],
       [False, False, False, False, False, False,  True,  True,  True,
         True,  True,  True]])

In [34]:
np.nonzero(arr == 5)

(array([0, 1, 2], dtype=int64), array([5, 5, 5], dtype=int64))

In [1]:
li = ['f']
type(li)

list

In [4]:
import sys

sys.path.append("../")
from codes.lpp_data import load_data

In [9]:
df, x, y, f, t, i = load_data("classification")

In [10]:
df.head()

SubjectID English_Level  Age  Sex(0-f,1-m)  IQ  Test_ID  Word_Number  \
1     rum_1            C2   30           0.0   7        1            2   
2     rum_1            C2   30           0.0   7        1            3   
3     rum_1            C2   30           0.0   7        1            4   
4     rum_1            C2   30           0.0   7        1            5   
5     rum_1            C2   30           0.0   7        1            6   

   FIXATION_COUNT  SKIP  TOTAL_READING_TIME  FIRST_FIXATION_DURATION  \
1               2     0                 214                    185.0   
2               1     0                 281                    281.0   
3               1     0                 250                    250.0   
4               1     0                 252                    252.0   
5               1     0                 226                    226.0   

   FIRST_FIXATION_X  FIRST_FIXATION_Y  FIRST_RUN_TOTAL_READING_TIME  \
1             233.8             111.1                         214.0   
2             335.7             117.7                         281.0   
3             416.2             124.6                         250.0   
4             518.2             107.8                         252.0   
5             605.4             104.7                         226.0   

   FIRST_SACCADE_AMPLITUDE  REGRESSION_IN  REGRESSION_OUT  \
1                     1.97            0.0             0.0   
2                     1.44            0.0             0.0   
3                     1.54            0.0             0.0   
4                     1.86            0.0             0.0   
5                     1.73            0.0             0.0   

   REGRESSION_OUT_FULL  REGRESSION_PATH_DURATION  
1                  0.0                     214.0  
2                  0.0                     281.0  
3                  0.0                     250.0  
4                  0.0                     252.0  
5                  0.0                     226.0

In [14]:
x

array([[  0.  ,   0.  ,   0.  , ..., 214.  ,   1.97, 214.  ],
       [  0.  ,   0.  ,   0.  , ..., 281.  ,   1.44, 281.  ],
       [  0.  ,   0.  ,   0.  , ..., 250.  ,   1.54, 250.  ],
       ...,
       [  0.  ,   0.  ,   0.  , ..., 415.  ,   0.67, 605.  ],
       [  0.  ,   0.  ,   0.  , ..., 225.  ,   5.24, 225.  ],
       [  0.  ,   0.  ,   0.  , ..., 428.  ,  24.13, 428.  ]])

In [16]:
arr = np.array([4, 14, -7, 41, 5, 4, 9])
np.ptp(arr) # range of array values

48